Update table prefix to `wp_pc_`
10up/plugin-check pull request #146
Opened 2023-04-14 12:38 UTC by jjgrainger

Closes #121

2023-04-17 15:34 UTC, spacedmonkey commented
@jjgrainger I think the original ticket's meaning was unclear. Developers / hosts can config there database config. See this [line](https://github.com/WordPress/wordpress-develop/blob/0276bfdd6d714810542866adf4325619b873db67/wp-config-sample.php#L68) 

So it should use the global $table_prefix.

2023-04-17 15:35 UTC, spacedmonkey commented on includes/Checker/Abstract_Check_Runner.php
>  			global $wpdb;
```suggestion
			global $wpdb, $table_prefix;
```

2023-04-17 15:36 UTC, spacedmonkey commented on includes/Checker/Abstract_Check_Runner.php
> +			$old_prefix = $wpdb->set_prefix( 'wp_pc_' );
```suggestion
			$old_prefix = $wpdb->set_prefix( $table_prefix . 'pc_' );
```

2023-04-17 15:37 UTC, spacedmonkey commented on includes/Admin/Admin_AJAX.php
> +		$old_prefix = $wpdb->set_prefix( 'wp_pc_' );
See https://github.com/10up/plugin-check/pull/146/files#r1168917663

2023-04-17 15:37 UTC, spacedmonkey commented on includes/Admin/Admin_AJAX.php
> +		if ( 'wp_pc_posts' === $wpdb->get_var( "SHOW TABLES LIKE 'wp_pc_posts'" ) || defined( 'WP_PLUGIN_CHECK_OBJECT_CACHE_DROPIN_VERSION' ) ) {
This same `wp_pc_posts` is used twice. It should be a variable.

2023-04-17 15:40 UTC, spacedmonkey commented on includes/Checker/Runtime_Environment_Setup.php
> +		$old_prefix = $wpdb->set_prefix( 'wp_pc_' );
Should be a variable, as `wp_pc_` is repeated a lot.

2023-04-17 15:52 UTC, spacedmonkey requested changes
I think the point of this PR is lost. Let's use the table_prefix global everywhere.

2023-04-17 16:58 UTC, felixarntz reviewed
Nothing to add here from my end to @spacedmonkey's feedback.

2023-04-18 15:41 UTC, spacedmonkey commented on includes/Admin/Admin_AJAX.php
> +		if ( 'wp_pc_posts' === $wpdb->get_var( "SHOW TABLES LIKE 'wp_pc_posts'" ) || defined( 'WP_PLUGIN_CHECK_OBJECT_CACHE_DROPIN_VERSION' ) ) {
```suggestion
		if ( $wpdb->posts === $wpdb->get_var( $wpdb->prepare( "SHOW TABLES LIKE %s",  $wpdb->posts ) ) || defined( 'WP_PLUGIN_CHECK_OBJECT_CACHE_DROPIN_VERSION' ) ) {
```

2023-04-18 15:42 UTC, spacedmonkey commented on includes/Checker/Runtime_Environment_Setup.php
> +		if ( 'wp_pc_posts' !== $wpdb->get_var( "SHOW TABLES LIKE 'wp_pc_posts'" ) ) {
```suggestion
		if ( $wpdb->posts === $wpdb->get_var( $wpdb->prepare( "SHOW TABLES LIKE %s",  $wpdb->posts ) ) ) {
```

2023-04-19 16:37 UTC, jjgrainger commented
Thnaks @spacedmonkey I've updated this based on your feedback and is ready for review.

2023-04-19 18:26 UTC, felixarntz approved these changes
Thanks for the updates @jjgrainger!

2023-04-20 09:16 UTC, spacedmonkey commented on includes/Checker/Runtime_Environment_Setup.php
> +		if ( $wpdb->posts === $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $wpdb->posts ) ) ) {
```suggestion
		if ( $wpdb->posts !== $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $wpdb->posts ) ) ) {
```

2023-04-20 09:18 UTC, spacedmonkey approved these changes
Looking good.

2023-04-20 14:33 UTC, merged