Make methods in abstract classes that should not be overridden `final`
10up/plugin-check pull request #162
Opened 2023-05-11 08:11 UTC by mukeshpanchal27

Closes #129 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

2023-05-11 13:22 UTC, spacedmonkey approved these changes

2023-05-11 16:00 UTC, felixarntz requested changes
@mukeshpanchal27 Almost good to go, however note that for the classes that should be made final, the actual _classes_ should be made final, not all the methods in that class.

The result will be more or less the same, but it's a lot of unnecessary code to make all methods final when you can instead make the entire class final. And we don't want people to extend those classes for the time being.

2023-05-11 16:00 UTC, felixarntz commented on includes/Admin/Admin_AJAX.php
> +	final public function add_hooks() {
Instead of making the methods in this class final, the entire class should be made final, see the issue description.

2023-05-11 16:00 UTC, felixarntz commented on includes/Admin/Admin_Page.php
> +	final public function __construct( Admin_AJAX $admin_ajax ) {
Same as above applies to this class and a few others in this PR. Please refer to the issue description.

2023-05-11 16:45 UTC, jjgrainger requested changes
Thanks @mukeshpanchal27 however it does not follow whats outlines in [the issue](https://github.com/10up/plugin-check/issues/129). 

- Most of the classes outlined in the issue can be made `final` instead of setting it to each method.
- I looks like the `Check_Context` class update is missing

2023-05-16 13:36 UTC, mukeshpanchal27 commented on includes/Admin/Admin_AJAX.php
> +	final public function add_hooks() {
Thanks @felixarntz, In https://github.com/10up/plugin-check/pull/162/commits/89830ecf2c521b02d3f7e2a140aa3bc78937fcfc i address this feedback. Can you please take a look.

2023-05-16 15:24 UTC, felixarntz approved these changes
Thanks @mukeshpanchal27, LGTM!

2023-05-16 15:32 UTC, jjgrainger approved these changes
Thanks @mukeshpanchal27 changes look good 👍

2023-05-16 15:35 UTC, merged