Add `No_Unfiltered_Uploads_Check` static check
10up/plugin-check pull request #211
Opened 2023-06-26 09:51 UTC by mukeshpanchal27

Closes #208 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-06-26 12:20 UTC, spacedmonkey commented on includes/Checker/Checks/No_Unfiltered_Uploads_Check.php
> +		$file      = self::file_str_contains( $php_files, 'ALLOW_UNFILTERED_UPLOADS' );
This should be a check to if is `define( 'ALLOW_UNFILTERED_UPLOADS` exists right? You could check to see if it is defined or use the constant right?

2023-06-26 12:21 UTC, spacedmonkey commented on tests/phpunit/testdata/plugins/test-plugin-unfiltered-uploads-with-errors/load.php
> +define( 'ALLOW_UNFILTERED_UPLOADS', true );
Add a check for something like this 

```
if ( defined( 'ALLOW_UNFILTERED_UPLOADS' ) ){
   return;
}
```

and 

```
if( ALLOW_UNFILTERED_UPLOADS ) {
   return;
}
```

2023-06-26 14:14 UTC, jjgrainger commented on includes/Checker/Checks/No_Unfiltered_Uploads_Check.php
> +		$file      = self::file_str_contains( $php_files, 'ALLOW_UNFILTERED_UPLOADS' );
I believe this is right as the intention is to flag any references to the constant whether it's being defined or used in the codebase.

This also matches the WP plugins implementation referenced in the AC's https://github.com/10up/plugin-check/issues/208

2023-06-26 14:16 UTC, jjgrainger requested changes
Thanks @mukeshpanchal27 overall looking good, would be good to add some additional test cases so we capture everything here.

2023-06-26 14:16 UTC, jjgrainger commented on tests/phpunit/testdata/plugins/test-plugin-unfiltered-uploads-with-errors/load.php
> +define( 'ALLOW_UNFILTERED_UPLOADS', true );
I agree, @mukeshpanchal27 let's add these examples to make sure the check picks up these cases.

2023-06-26 17:40 UTC, felixarntz approved these changes
Thanks @mukeshpanchal27, nothing to add from my end other than the test plugin change that Jonny mentioned. Also, this has to be refreshed with latest `trunk` now that #209 has been merged, to fix the merge conflict.

I'll mark this as approved already, but please address the one point of feedback :)

2023-06-27 05:04 UTC, mukeshpanchal27 commented on tests/phpunit/testdata/plugins/test-plugin-unfiltered-uploads-with-errors/load.php
> +define( 'ALLOW_UNFILTERED_UPLOADS', true );
Thanks for the feedback. Address in https://github.com/10up/plugin-check/pull/211/commits/5e076c03190b75af9cf1032c66d05ca60b25ebd2

2023-06-27 11:59 UTC, jjgrainger reviewed
Thanks @mukeshpanchal27 approved

2023-06-27 11:59 UTC, jjgrainger approved these changes

2023-06-27 12:00 UTC, merged