Incorrect display of `readme.txt` instead of `readme.md` in Plugin Readme check
10up/plugin-check pull request #239
Opened 2023-08-01 10:46 UTC by mukeshpanchal27

In issue #195, it was allowed to use a `readme.md` file for plugin. However, when someone uses the `readme.md` file and runs the plugin checks, the plugin incorrectly displays `readme.txt` as the file name instead of the actual `readme.md` file.

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have added tests to cover my change.
- [x] All new and existing tests pass.

2023-08-01 14:20 UTC, joemcgill commented
I'm curious about the initial intent for this check. I think it's still a requirement for a plugin to have a `readme.txt` file, even if it also includes a `readme.md`, since the header in the txt version is the one used for parsing out plugin info like version, tested up to, etc. 

See: https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#readme-header-information

2023-08-01 15:19 UTC, felixarntz commented
@joemcgill I thought so too, but someone else (I don't recall, maybe it was @swissspidy or @westonruter?) pointed out that wordpress.org, despite not well documenting it, actually supports using `readme.md` as well as the _actual_ .org readme file. So if you don't include `readme.txt` but include `readme.md`, wordpress.org will try to parse its contents apparently. Of course that only works if you format `readme.md` correctly for that purpose, not if it's a general readme e.g. for just GitHub.

2023-08-01 16:44 UTC, westonruter commented
> I thought so too, but someone else (I don't recall, maybe it was @swissspidy or @westonruter?) pointed out that wordpress.org

I think it was actually @johnbillion: https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/

For the AMP plugin we initially tried just going with `README.md` alone in https://github.com/ampproject/amp-wp/pull/5807, but in https://github.com/ampproject/amp-wp/pull/5815 we re-introduced the `readme.txt` but [created it](https://github.com/ampproject/amp-wp/blob/cebab46e081f55815f4be83529b89feee34f3020/bin/transform-readme.php) at build time out of the `README.md` due to various WordPress-specific issues with the format.

2023-08-01 17:19 UTC, joemcgill commented
That's really interesting, I didn't realize this was supported. Still, I'm curious if the lack of a README.txt file would get flagged in the plugin review process, and if so, is something we should still include as a check in our plugin?

2023-08-01 17:52 UTC, felixarntz commented
I don't think we need to specifically check for `readme.txt`, as either works. This is also confirmed by the other plugin checker code, which supports either file extension in the same way: https://github.com/WordPress/plugin-check/blob/trunk/plugin.php#L76

2023-08-01 18:01 UTC, felixarntz requested changes
Thanks @mukeshpanchal27, a few minor bits of feedback below to make the file paths consistent with other checks (relative to the plugin's directory).

2023-08-01 18:01 UTC, felixarntz commented on includes/Checker/Checks/Plugin_Readme_Check.php
> +					'file' => $file,
This needs to also be the path relative to the plugin's directory, similar to other checks.
```suggestion
					'file' => str_replace( $result->plugin()->path(), '', $file ),
```

2023-08-01 18:01 UTC, felixarntz commented on includes/Checker/Checks/Plugin_Readme_Check.php
> +				),
I think we can simplify this since the concrete file path is part of the data below anyway.
```suggestion
				__( 'The readme appears to contain default text.', 'plugin-check' ),
```

2023-08-01 18:01 UTC, felixarntz commented on includes/Checker/Checks/Plugin_Readme_Check.php
> +					'file' => $file,
See above:
```suggestion
					'file' => str_replace( $result->plugin()->path(), '', $file ),
```

2023-08-01 18:01 UTC, felixarntz commented on includes/Checker/Checks/Plugin_Readme_Check.php
> +				),
See above:
```suggestion
				__( 'Your plugin has an invalid license declared. Please update your readme with a valid SPDX license identifier.', 'plugin-check' ),
```

2023-08-01 18:01 UTC, felixarntz commented on includes/Checker/Checks/Plugin_Readme_Check.php
> +					'file' => $file,
See above:
```suggestion
					'file' => str_replace( $result->plugin()->path(), '', $file ),
```

2023-08-01 18:01 UTC, felixarntz commented on includes/Checker/Checks/Plugin_Readme_Check.php
> +					'file' => $file,
See above:
```suggestion
					'file' => str_replace( $result->plugin()->path(), '', $file ),
```

2023-08-01 18:01 UTC, felixarntz commented on includes/Checker/Checks/Plugin_Readme_Check.php
> +				),
See above:
```suggestion
				__( 'The Stable Tag in your readme file does not match the version in your main plugin file.', 'plugin-check' ),
```

2023-08-02 07:03 UTC, mukeshpanchal27 commented
Thanks all the the review and details. The PR is ready for review.

2023-08-02 10:25 UTC, mukeshpanchal27 commented
The Plugin Checker currently checks all files, including in subfolders. However, we should modify the check to only consider files in the root directory for `readme.txt` and `readme.md` checks. 

WordPress allows and parse `readme.txt` and `readme.md` files in root directory of the plugin. Therefore, we will adjust the Plugin Checker accordingly to focus only on root directory files.

For instance, when we checked the WooCommerce plugin, the Plugin Checker returned an array of files as follows:

```
/var/www/html/wp-content/plugins/woocommerce/Array
(
    [1511] => /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/readme.txt
    [1668] => /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/assets/js/base/README.MD
    [3531] => /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/readme.txt
    [3962] => /var/www/html/wp-content/plugins/woocommerce/readme.txt
)
```

The specific error highlighted was:

<h4>FILE: packages/action-scheduler/readme.txt</h4>

Line | Column | Type | Code | Message
-- | -- | -- | -- | --
0 | 0 | WARNING | stable_tag_mismatch | The Stable Tag in your readme file does not match the version in your main plugin file.

We will update the Plugin Checker to only report errors for `readme.txt` and `readme.md` files that are directly in the root directory of the plugin and not in subfolders.

@felixarntz @joemcgill If the above makes sense, then I will open the follow-up issue and start working on it. Thanks.

2023-08-02 15:05 UTC, felixarntz commented
Thanks @mukeshpanchal27, that's a great catch! +1 to opening a follow-up issue and PR to fix it so that the plugin checker only considers readme files in the root directory.

2023-08-02 15:05 UTC, felixarntz approved these changes
LGTM, let's open a follow-up PR for the other problem you discovered above. Thank you @mukeshpanchal27!

2023-08-02 17:06 UTC, joemcgill approved these changes

2023-08-03 04:06 UTC, merged