Plugin check UX improvement for results
10up/plugin-check pull request #326
Opened 2023-11-28 06:04 UTC by jakaria-istauk

2023-12-12 11:04 UTC, mukeshpanchal27 requested changes
Thanks @jakaria-istauk for the PR.

- Ran `npm run lint-js -- --fix` to fix the JS lint issue and uploaded the changes.
- Left some feedback that needs to address.

2023-12-12 11:04 UTC, mukeshpanchal27 commented on assets/js/plugin-check-admin.js
> +		//Adding Open All/Collapse All button
```suggestion
		// Adding Open All/Collapse All button.
```

Inline comment should be end with period.

🔢 Apply same to other places also.

2023-12-12 11:04 UTC, mukeshpanchal27 commented on assets/js/plugin-check-admin.js
> +				'<div><button style="margin-top:1.33em;" class="button button-primary clollaps-all" data-state="open">Clollaps All</button></div>' +
All test should be translatable. You can add string in `wp_localize_script`.

2023-12-12 11:04 UTC, mukeshpanchal27 commented on templates/results-table.php
> +	<button class="collapse-btn" data-state="collapse"><?php esc_html_e( 'Collapse' ); ?></button>
Text domain is missing for `Collapse` string.

2023-12-12 16:48 UTC, jakaria-istauk commented
hi @mukeshpanchal27 , 
Thanks for your feedback. I gave an update according to your feedback.

2024-06-28 20:22 UTC, davidperezgar commented
I'd suggest to make an arrow like it works the accordions, so it's minimal interface.
Like this one: `<span class="dashicons dashicons-arrow-down-alt2"></span>`

2025-04-24 21:22 UTC, closed without merging