Add Enqueued_Styles_Size_Check
10up/plugin-check pull request #333
Opened 2023-12-11 10:02 UTC by ernilambar

Fixes https://github.com/WordPress/plugin-check/issues/19

**Note:**

- I have added tests to cover my change.
- All new and existing tests pass.

2024-06-26 21:13 UTC, davidperezgar commented
I've changed the tag so the Performance Team can review it.

2024-07-01 11:39 UTC, swissspidy commented on includes/Checker/Checks/Enqueued_Styles_Size_Check.php
> +					),
I just realized `Enqueued_Scripts_Size_Check` has the same flaw, so would be great to make the string translatable there as well.

```suggestion
					sprintf(
						/* translators: 1: style file size. 2: tested URL. 3: threshold file size. */
						__( 'This style has a size of %1$s which in combination with the other styles enqueued on %2$s exceeds the style size threshold of %3$s.', 'plugin-check' )
						size_format( $plugin_style['size'] ),
						$url,
						size_format( $this->threshold_size )
					),
```

2024-07-01 11:41 UTC, swissspidy approved these changes
IDK why this wasn't picked up earlier, apologies!

Given that this adapts `Enqueued_Scripts_Size_Check` for styles, it looks pretty straightforward.

Just one suggestion regarding i18n.

2024-07-01 11:43 UTC, swissspidy commented
Related:

* #74

Maybe we could add this here as well from the beginning?

2024-07-01 12:40 UTC, mukeshpanchal27 commented on includes/Checker/Checks/Enqueued_Styles_Size_Check.php
> + * @since n.e.x.t
Add specific version number as we don't have shell script that change `n.e.x.t` to upcoming version when releasing.

May be `1.0.2` is next version

2024-07-01 12:45 UTC, mukeshpanchal27 requested changes

2024-07-01 12:45 UTC, mukeshpanchal27 commented on includes/Checker/Checks/Enqueued_Styles_Size_Check.php
> +						__( 'This style has a size of %1$s which in combination with the other styles enqueued on %2$s exceeds the style size threshold of %3$s.', 'plugin-check' )
```suggestion
						__( 'This style has a size of %1$s which in combination with the other styles enqueued on %2$s exceeds the style size threshold of %3$s.', 'plugin-check' ),
```

It shows error.

2024-07-01 13:03 UTC, swissspidy commented on includes/Checker/Checks/Enqueued_Styles_Size_Check.php
> +						__( 'This style has a size of %1$s which in combination with the other styles enqueued on %2$s exceeds the style size threshold of %3$s.', 'plugin-check' )
Whoops my bad :)

2024-07-01 15:19 UTC, swissspidy commented
In a separate PR we can look into creating an abstract class or so to reduce code repetition between this class and `Enqueued_Scripts_Size_Check`

2024-07-01 20:52 UTC, westonruter approved these changes

2024-07-02 04:11 UTC, mukeshpanchal27 approved these changes

2024-07-02 04:11 UTC, merged