Remove repo specific CoC file.
10up/plugin-check pull request #431
Opened 2024-02-16 01:38 UTC by desrosj

This removes the repository specific `CODE_OF_CONDUCT.md` file in favor of the newly added version maintained as the organization's default within the WordPress/.github repository.

While this file will not be included in `git clone`s, it will be displayed on the repository's main page and anywhere else GitHub includes a Code of Conduct link.

This change enables more consistent messaging for the community code of conduct, and allows the file to be updated in one location for all repositories under the WordPress organization.

See https://github.com/WordPress/.github/pull/1.

2024-02-16 08:12 UTC, swissspidy approved these changes

2024-02-20 06:32 UTC, mukeshpanchal27 requested changes
Thanks @desrosj for the PR!

We should remove the `CODE_OF_CONDUCT.md` references from files:
- [CONTRIBUTING.md](https://github.com/WordPress/plugin-check/blob/7c3f6d4c2683306d7f62098962bb07c8dfb58117/CONTRIBUTING.md?plain=1#L14)
- [.distignore](https://github.com/WordPress/plugin-check/blob/7c3f6d4c2683306d7f62098962bb07c8dfb58117/.distignore#L25)
- [.gitattributes](https://github.com/WordPress/plugin-check/blob/7c3f6d4c2683306d7f62098962bb07c8dfb58117/.gitattributes#L25)

2024-02-20 13:37 UTC, desrosj commented
Thanks, @mukeshpanchal27! I've gone and corrected those as well.

2024-02-21 04:47 UTC, mukeshpanchal27 approved these changes

2024-02-21 04:47 UTC, merged