Added `@global` documentation in several files
10up/plugin-check pull request #602
Opened 2024-08-31 15:41 UTC by shail-mehta

Fixes: https://github.com/WordPress/plugin-check/issues/601

2024-08-31 23:30 UTC, ernilambar approved these changes

2024-09-01 03:30 UTC, mukeshpanchal27 requested changes

2024-09-01 03:30 UTC, mukeshpanchal27 commented on includes/Admin/Admin_AJAX.php
> +	 * @global string $table_prefix The database table prefix.
```suggestion
	 * @global wpdb   $wpdb         WordPress database abstraction object.
	 * @global string $table_prefix The database table prefix.
```

2024-09-01 03:30 UTC, mukeshpanchal27 commented on includes/Checker/Abstract_Check_Runner.php
> +	 * @global string $table_prefix The database table prefix.
```suggestion
	 * @global wpdb   $wpdb         WordPress database abstraction object.
	 * @global string $table_prefix The database table prefix.
```

2024-09-01 03:30 UTC, mukeshpanchal27 commented on includes/Checker/Runtime_Environment_Setup.php
> +	 * @global WP_Filesystem_Base $wp_filesystem WordPress filesystem subclass.
```suggestion
	 * @global wpdb               $wpdb          WordPress database abstraction object.
	 * @global string             $table_prefix  The database table prefix.
	 * @global WP_Filesystem_Base $wp_filesystem WordPress filesystem subclass.
```

2024-09-01 03:55 UTC, shail-mehta commented
Thank you for your feedback. I have made the requested changes.

2024-09-02 03:31 UTC, mukeshpanchal27 approved these changes

2024-09-02 03:31 UTC, merged