Add check for unsupported plugin name in plugin header field
10up/plugin-check pull request #825
Opened 2024-12-10 06:59 UTC by ernilambar

Fixes https://github.com/WordPress/plugin-check/issues/805

2024-12-10 07:08 UTC, ernilambar commented
Tests are failing due to unrelated issue with this PR.

2024-12-10 17:36 UTC, davidperezgar approved these changes

2025-01-07 14:22 UTC, swissspidy approved these changes

2025-01-07 15:12 UTC, ernilambar commented
@frantorres  has suggested to modify the conditional and make less strict. Like:

Check if plugin name "has at least 5 latin letters (A-z), numbers, spaces, and hyphens" and not worry if there are other non valid characters around.

2025-01-07 18:43 UTC, davidperezgar commented
I think that you meant @frantorres

2025-01-08 09:55 UTC, ernilambar commented
I have updated the conditional to make less strict. Current message looks off due to new conditional:
```
The "Plugin Name" header in the plugin file is not valid. It may only contain latin letters (A-z), numbers, spaces, and hyphens.
```
Can you please suggest updated message?

2025-01-08 10:34 UTC, frantorres commented
Maybe
> The "Plugin Name" header in the plugin file is not valid. It needs to contain at least 5 latin letters (a-Z) and/or numbers. This is necessary because the initial plugin slug is generated from the name.

2025-01-08 10:35 UTC, frantorres requested changes

2025-01-08 10:35 UTC, frantorres commented on includes/Checker/Checks/Plugin_Repo/Plugin_Header_Fields_Check.php
> +				$valid_chars_count = preg_match_all( '/[a-z0-9-]/i', $plugin_header['Name'] );
The regex might be` /[a-zA-Z0-9]/i`

2025-01-08 10:35 UTC, frantorres commented on includes/Checker/Checks/Plugin_Repo/Plugin_Header_Fields_Check.php
> +							__( 'The "%s" header in the plugin file is not valid. It may only contain latin letters (A-z), numbers, spaces, and hyphens.', 'plugin-check' ),
The "%s" header in the plugin file is not valid. It needs to contain at least 5 latin letters (a-Z) and/or numbers. This is necessary because the initial plugin slug is generated from the name.

2025-01-08 10:52 UTC, frantorres approved these changes

2025-01-08 10:53 UTC, merged